spring.application.name=attendance-platform

spring.datasource.url=jdbc:postgresql://localhost:5433/attendance_platform
spring.datasource.username=avanthika
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true